name: Prod

on:
  push:
    branches:
      - main

jobs:
  build-prod:
    name: Build and Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: npm i

      - name: Build
        run: ionic cordova build browser -l

      - name: Deploy
        run: firebase deploy -- only hosting
