name: Prod

on:
  push:
    branches:
      -main

jobs:
  uild-einstein:
    name: Build and Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: ionic cordova build browser -l

      - name: Deploy
        run: firebase deploy -- only hosting
