name: Prod

on:
  push:
    branches:
      -main

jobs:
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: ionic cordova build browser -l

      - name: Deploy
        run: firebase deploy -- only hosting
